name: "Build & Release"

on:
  pull_request:
    branches:
      - main
      - master
  push:
    branches:
      - main
      - master
      - develop

jobs:
  build:
    name: Build & Release
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "17"

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          architecture: x64

      - name: Build Flutter app (Android)
        run: flutter build apk --release --split-per-abi

      # Uncomment and modify the following steps if you want to build for iOS as well
      # - name: Build Flutter app (iOS)
      #   run: |
      #     flutter build ios --no-codesign
      #     cd build/ios/iphoneos
      #     mkdir Payload
      #     cd Payload
      #     ln -s ../Runner.app
      #     cd ..
      #     zip -r app.ipa Payload

      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/release/*.apk" # Ensure the correct path to your APK files
          # artifacts: "build/web/*"  # Uncomment if building for web
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.TOKEN }} # Use the correct secret token name
